### PR TITLE
Wrap of index.html

### PR DESCRIPTION
**Pull request by pjpmosteiro**
Hi! Reviewing the code I wrapped the code of index.html for a better reading.
Good job with the script, funny and practical :) 👍

### CODE REVIEW

**Comment by davorpa** [comment]
Well done @pjpmosteiro, It's a good practice __*indent code*__ and follow a style guide.

A tip: for this things are tools like Prettier that helping you doing it at globally project scope, not only for index.html.

By other hand, I think that this kind of refactoring difficult the merge of other PR so I think it's better treath them in a branch apart or at lastest instance.

Are you agree?

**Comment by pjpmosteiro** [comment]
> Well done @pjpmosteiro, It's a good practice **_indent code_** and follow a style guide.
> 
> A tip: for this things are tools like Prettier that helping you doing it at globally project scope, not only for index.html.
> 
> By other hand, I think that this kind of refactoring difficult the merge of other PR so I think it's better treath them in a branch apart or at lastest instance.
> 
> Are you agree?

Hi, davorpa. Of course I can use Prettier, but I don´t wanna use it, and I have very strong reasons to do it. 

By the way, I´ve been following you in the GitHub network and found that many of your issues or PR have been reported as they are unnecesary or simply spam. I kindly ask you to please stop doing that kind of moves, so we can keep GitHub as what is meant: a collaborative platform. Thank you :)

**Comment by davorpa** [comment]
One thing more @pjpmosteiro

You modify the `docs/index.html` instead of doing in `public/index.html` and after pack the app with provided `npm` commands. So I think that this PR maybe incomplete.

I suggest you complete it ;)

**Comment by pjpmosteiro** [comment]
Hi @davorpa. The PR is done to a repository that is not in your account (and you forked), please, try not to exceed in your comments. 
Also, please, DO NOT tell others how to do their job, thank you. 
I don´t mean to be aggresive, but "suggesting ;" others to do something is not the best way to contribute. Doing such an extensive review of a simple refactoring....
Also, remember that I tested it before pushing it.
.

**Comment by davorpa** [comment]
Estimado Pablo,

Y esto te lo escribo yo también en español. Tu también eres conocido por tu pasado, ¿o no recuerdas arrepentirte de ciertos artículos en blogs?

I "suggest you" DO NOT misunderstand my words due to incomplete thirth party opinions.

My humble way to contribute... suggesting you that the right file is in `public` folder. If you want complete it, if not... close this PR as you did.

Have a great day ;)

**Comment by pjpmosteiro** [comment]
> Estimado Pablo,
> 
> Y esto te lo escribo yo también en español. Tu también eres conocido por tu pasado, ¿o no recuerdas arrepentirte de ciertos artículos en blogs?
> 
> I "suggest you" DO NOT misunderstand my words due to incomplete thirth party opinions.
> 
> My humble way to contribute... suggesting you that the right file is in `public` folder. If you want complete it, if not... close this PR as you did.
> 
> Have a great day ;)

Hi @davorpa. I don´t think your suggest is valid, as I closed the PR, that´s because I didn´t altered the tree of the project, so I think that should go on another request, as is not related with the purpose of this request.

 Altought, trust me, I´m very aware about the data published at my name in the Net (the blog you talk about is on my GitHub profile, and I very proud of it, thanks for the visit :) ). My past is known as I want everyone to know it, do a social research if you want.

Otherwise, I think this is not the site to have this conversation, this is a place for coding, not arguing. If you want to keep talking about this, please, talk me on Twitter (l3x1um) or by mail. Thanks for the suggestion. 
This is my last message here.

Have a nice day ;)

**Pull request closed without merging**
